Automation to create a new docker tag (#503)
* Automation to create a new docker tag

* adding docker develop

* correction in release and develop docker workflow

* try tooljet changes

* try tooljet changes with redis

* Fix redis issue and moved entrypoint to a separate file

* try-tooljet dockerfile base image correction

* Automation correction

diff --git a/.github/workflows/tooljet-release-docker-image-build.yml b/.github/workflows/tooljet-release-docker-image-build.yml
--- a/.github/workflows/tooljet-release-docker-image-build.yml
+++ b/.github/workflows/tooljet-release-docker-image-build.yml
@@ -7,8 +7,8 @@ on:
   workflow_dispatch:
     inputs:
       job-to-run:
-        description: Enter the job name (tooljet-ee)
-        options: ['tooljet-ee']
+        description: Enter the job name (tooljet, try-tooljet)
+        options: ["tooljet", "try-tooljet"]
         required: true
       image:
         description: "Enter the latest image tag"
@@ -16,7 +16,7 @@ on:
 
 jobs:
 
-  build-tooljet-ee-image:
+  build-tooljet-image:
     runs-on: ubuntu-latest
     if: "${{ github.event.release }}"
 
@@ -61,7 +61,7 @@ jobs:
           context: .
           file: docker/production.Dockerfile
           push: true
-          tags: tooljet/tooljet-ee:${{ github.event.release.tag_name }},tooljet/tooljet-ee:latest
+          tags: tooljet/tooljet-ee:${{ github.event.release.tag_name }},tooljet/tooljet-ee:latest,tooljet/tooljet:${{ github.event.release.tag_name }},tooljet/tooljet:latest
           platforms: linux/amd64
         env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
@@ -70,19 +70,90 @@ jobs:
       - name: Send Slack Notification
         run: |
           if [[ "${{ job.status }}" == "success" ]]; then
-            message="Job '${{ env.JOB_NAME }}' succeeded! docker image tooljet/tooljet-ee:${{ github.event.release.tag_name }}"
+            message="Job '${{ env.JOB_NAME }}' succeeded! docker image tooljet/tooljet-ee:${{ github.event.release.tag_name }} \n tooljet/tooljet:${{ github.event.release.tag_name }}"
           else
-            message="Job '${{ env.JOB_NAME }}' failed! docker image tooljet/tooljet-ee:${{ github.event.release.tag_name }}"
+            message="Job '${{ env.JOB_NAME }}' failed! docker image tooljet/tooljet-ee:${{ github.event.release.tag_name }} \n tooljet/tooljet:${{ github.event.release.tag_name }}"
           fi
 
           curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$message\"}" ${{ secrets.SLACK_WEBHOOK_URL }}                   
 
 
-  #Below code helps to trigger the workflow separately
-
-  tooljet-ee:
+  try-tooljet-image-build:
     runs-on: ubuntu-latest
-    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.job-to-run == 'tooljet-ee' }}
+    needs: build-tooljet-image
+    if: ${{ needs.build-tooljet-image.result == 'success' }}
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          ref: develop
+
+      # Create Docker Buildx builder with platform configuration
+      - name: Set up Docker Buildx
+        run: |
+          mkdir -p ~/.docker/cli-plugins
+          curl -SL https://github.com/docker/buildx/releases/download/v0.11.0/buildx-v0.11.0.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
+          chmod a+x ~/.docker/cli-plugins/docker-buildx
+          docker buildx create --name mybuilder --platform linux/arm64,linux/amd64,linux/amd64/v2,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
+          docker buildx use mybuilder
+
+      - name: Set DOCKER_CLI_EXPERIMENTAL
+        run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV
+
+      - name: use mybuilder buildx
+        run: docker buildx use mybuilder
+
+      - name: Docker Login
+        uses: docker/login-action@v1
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Check if Docker image is present
+        id: check-image-presence
+        run: |
+          response=$(curl -s "https://hub.docker.com/v2/repositories/tooljet/tooljet-ce/tags/${{ github.event.release.tag_name }}")
+          if [[ $? -ne 0 ]]; then
+            echo "Failed to fetch JSON response. Stopping workflow execution."
+            exit 1
+          fi
+
+          if [[ $response == *"tag '${{ github.event.release.tag_name }}' not found"* ]]; then
+            echo "Docker image tag '${{ github.event.release.tag_name }}' not present."
+            exit 1
+          else
+            echo "Docker image tag '${{ github.event.release.tag_name }}' is present."
+          fi
+
+      - name: Build and Push Docker image
+        uses: docker/build-push-action@v4
+        with:
+          context: .
+          file: docker/try-tooljet.Dockerfile
+          push: true
+          tags: tooljet/try:${{ github.event.release.tag_name }},tooljet/try:latest
+          platforms: linux/amd64
+        env:
+          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Send Slack Notification
+        run: |
+          if [[ "${{ job.status }}" == "success" ]]; then
+            message="Job '${{ env.JOB_NAME }}' succeeded! tooljet/try:${{ github.event.release.tag_name }}"
+          else
+            message="Job '${{ env.JOB_NAME }}' failed! tooljet/try:${{ github.event.release.tag_name }}"
+          fi
+
+          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$message\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
+
+
+  #Below code helps to trigger the workflow manually
+
+  tooljet:
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.job-to-run == 'tooljet' }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -124,7 +195,7 @@ jobs:
           context: .
           file: docker/production.Dockerfile
           push: true
-          tags: tooljet/tooljet-ee:${{ github.event.inputs.image }},tooljet/tooljet-ee:latest
+          tags: tooljet/tooljet-ee:${{ github.event.inputs.image }},tooljet/tooljet-ee:latest,tooljet/tooljet:${{ github.event.inputs.image }},tooljet/tooljet:latest
           platforms: linux/amd64
         env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
@@ -133,9 +204,62 @@ jobs:
       - name: Send Slack Notification
         run: |
           if [[ "${{ job.status }}" == "success" ]]; then
-            message="Job '${{ env.JOB_NAME }}' succeeded! docker image tooljet/tooljet-ee:${{ github.event.inputs.image }}"
+            message="Job '${{ env.JOB_NAME }}' succeeded! docker image tooljet/tooljet-ee:${{ github.event.inputs.image }} & tooljet/tooljet:${{ github.event.inputs.image }}"
           else
-            message="Job '${{ env.JOB_NAME }}' failed! docker image tooljet/tooljet-ee:${{ github.event.inputs.image }}"
+            message="Job '${{ env.JOB_NAME }}' failed! docker image tooljet/tooljet-ee:${{ github.event.inputs.image }} & tooljet/tooljet:${{ github.event.inputs.image }}"
+          fi
+
+          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$message\"}" ${{ secrets.SLACK_WEBHOOK_URL }}          
+
+  try-tooljet:
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.job-to-run == 'try-tooljet' }}
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          ref: main
+
+      # Create Docker Buildx builder with platform configuration
+      - name: Set up Docker Buildx
+        run: |
+          mkdir -p ~/.docker/cli-plugins
+          curl -SL https://github.com/docker/buildx/releases/download/v0.11.0/buildx-v0.11.0.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
+          chmod a+x ~/.docker/cli-plugins/docker-buildx
+          docker buildx create --name mybuilder --platform linux/arm64,linux/amd64,linux/amd64/v2,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
+          docker buildx use mybuilder
+
+      - name: Set DOCKER_CLI_EXPERIMENTAL
+        run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV
+
+      - name: use mybuilder buildx
+        run: docker buildx use mybuilder
+
+      - name: Docker Login
+        uses: docker/login-action@v1
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Build and Push Docker image
+        uses: docker/build-push-action@v4
+        with:
+          context: .
+          file: docker/try-tooljet.Dockerfile
+          push: true
+          tags: tooljet/try:${{ github.event.inputs.image }},tooljet/try:latest
+          platforms: linux/amd64
+        env:
+          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Send Slack Notification
+        run: |
+          if [[ "${{ job.status }}" == "success" ]]; then
+            message="Job '${{ env.JOB_NAME }}' succeeded! tooljet/try:${{ github.event.inputs.image }}"
+          else
+            message="Job '${{ env.JOB_NAME }}' failed! tooljet/try:${{ github.event.inputs.image }}"
           fi
 
           curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$message\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
