Modified the code make the check if the image is present

diff --git a/.github/workflows/try-tooljet.yml b/.github/workflows/try-tooljet.yml
--- a/.github/workflows/try-tooljet.yml
+++ b/.github/workflows/try-tooljet.yml
@@ -1,10 +1,12 @@
-
 name: Try-Tooljet Docker Image
 
 on:
-  release:
+  release: 
+    types: [published]
     branches:
       - main
+
+  workflow_dispatch:
 
 jobs:
   build-and-push:
@@ -14,31 +16,35 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Wait for Docker image
-        id: wait-for-image
-        run: |
-          retries=0
-          max_retries=10
-          while [[ "$(docker images -q tooljet/tooljet-ce:${{ github.event.release.tag_name }})" == "" ]]; do
-            retries=$((retries+1))
-            if [[ $retries -gt $max_retries ]]; then
-              echo "Docker image not found. Maximum retries exceeded. Stopping workflow execution."
-              exit 1
-            fi
-            sleep 5
-          done
-
       - name: Set DOCKER_CLI_EXPERIMENTAL
         run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
-      - name: Build and Push Docker image
-        env:
-          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Docker Login
+        uses: docker/login-action@v1
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+          
+      - name: Check if Docker image is present
+        id: check-image-presence
         run: |
-          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
-          docker buildx build --platform=linux/amd64 -f docker/try-tooljet.Dockerfile . -t tooljet/try:lastest
-          docker push tooljet/try:lastest
+          response=$(curl -s "https://hub.docker.com/v2/repositories/tooljet/tooljet-ce/tags/${{ github.event.release.tag_name }}")
+          if [[ $? -ne 0 ]]; then
+            echo "Failed to fetch JSON response. Stopping workflow execution."
+            exit 1
+          fi
+
+          if [[ $response == *"tag '${{ github.event.release.tag_name }}' not found"* ]]; then
+            echo "Docker image tag '${{ github.event.release.tag_name }}' not present."
+            exit 1
+          else
+            echo "Docker image tag '${{ github.event.release.tag_name }}' is present."
+          fi
+
+      - name: Build and Push Docker image
+        run: |
+          docker buildx build --platform=linux/amd64 -f docker/try-tooljet.Dockerfile . -t tooljet/tj-osv:test
+          docker push tooljet/tj-osv:test
